### ISSUE TITLE
python3.7-llvmlite-artiq fails to build

### ISSUE THREAD

**Issue by kaolpr** [m-labs/nix-scripts#8]
I'm trying to build ARTIQ using Nix, however `python3.7-llvmlite-artiq` fails to build. Log attached.
The command was: `nix-shell -I artiqSrc=$(pwd)/artiq nix-scripts/artiq/shell.nix`.

[0cg7p1z907q6brnrm58rnqmvvi88gh-python3.7-llvmlite-artiq.drv.txt](https://github.com/m-labs/nix-scripts/files/2918598/0cg7p1z907q6brnrm58rnqmvvi88gh-python3.7-llvmlite-artiq.drv.txt)

**Comment by sbourdeauducq** [comment]
What nixpkgs version?

**Comment by sbourdeauducq** [comment]
BTW, if you use 18.09 there are binaries available and you don't need to compile. Or are you trying to use the latest version on purpose?

**Comment by kaolpr** [comment]
19.09pre170896.6e5caa3f8ac
It was not on purpose, I just followed instructions from [Developing ARTIQ](https://m-labs.hk/artiq/manual-master/developing.html)

**Comment by sbourdeauducq** [comment]
Well the doc does say "Those channels track nixpkgs 18.09", though it doesn't explain what to do.

**Comment by kaolpr** [comment]
Ok, I missed that. However it would be very helpful for Nix newcomers (like me) to make a note that action is needed.

**Comment by sbourdeauducq** [comment]
Yep. What exact command did you use with standalone nix?

**Comment by kaolpr** [comment]
I'm not sure if this is the right way to go, but I removed channel nixpgs and added it pointing to the 18.09 version:
```
nix-channel --remove nixpkgs
nix-channel --add https://nixos.org/channels/nixpkgs-18.09-darwin nixpkgs
nix-channel --update
```

**Comment by sbourdeauducq** [comment]
Sounds fine. Using Darwin?

**Comment by sbourdeauducq** [comment]
https://github.com/m-labs/artiq/commit/26dd4e51600878583abd3023a5a1bf95533c3c97

**Comment by kaolpr** [comment]
@sbourdeauducq Nope, thought it meant something different.
